<?php

namespace AppBundle\UuidSerializer;

class UuidName
{
	public static function getPlanetName($data)
	{
        $planetNames = array_merge(self::$periodicNames, self::$fabricNames);
		$planetUniqueUuid = implode('', $data);
		$nameCombinations = count(self::$colorNames) * count($planetNames);
		$combination = 0;
		foreach (str_split($planetUniqueUuid) as $letter) {
			$combination = ($combination + 7*ord($letter)) % $nameCombinations;
		}
		$nameIndex = $combination % count($planetNames);
		$colorIndex = $combination % count(self::$colorNames);
		return ucfirst(self::$colorNames[$colorIndex]) . ' ' .$planetNames[$nameIndex];
	}

	private static $periodicNames = [
		"Actinium",
		"Aluminum",
		"Antimony",
		"Argon",
		"Barium",
		"Berkelium",
		"Beryllium",
		"Bismuth",
		"Bohrium",
		"Boron",
		"Bromine",
		"Cadmium",
		"Calcium",
		"Californium",
		"Carbon",
		"Cerium",
		"Cesium",
		"Chlorine",
		"Chromine",
		"Cobalt",
		"Copper",
		"Curium",
		"Darmstadtium",
		"Dubnium",
		"Dysprosium",
		"Einsteinium",
		"Erbium",
		"Europium",
		"Fermuim",
		"Fluorine",
		"Francium",
		"Gadolinium",
		"Gallium",
		"Germanium",
		"Gold",
		"Hafnium",
		"Hassium",
		"Helium",
		"Holmium",
		"Hydrogen",
		"Indium",
		"Iodine",
		"Iridium",
		"Iron",
		"Krypton",
		"Lanthanum",
		"Lawrencium",
		"Lead",
		"Lithium",
		"Lutetium",
		"Magnesium",
		"Manganese",
		"Meitnerium",
		"Mendelevium",
		"Mercury",
		"Molybdenum",
		"Neodymium",
		"Neon",
		"Neptunium",
		"Nickel",
		"Niobium",
		"Nitrogen",
		"Nobellium",
		"Osmium",
		"Oxygen",
		"Palladium",
		"Phosphorus",
		"Platinum",
		"Plutonium",
		"Polonium",
		"Potassium",
		"Praseodymium",
		"Promethium",
		"Protactinium",
		"Radium",
		"Radon",
		"Rhenium",
		"Rhodium",
		"Rubidium",
		"Ruthenium",
		"Rutherfordium",
		"Samarium",
		"Scandium",
		"Seaborgium",
		"Selenium",
		"Silicon",
		"Silver",
		"Sodium",
		"Strontium",
		"Sulfur",
		"Tantalum",
		"Technetium",
		"Tellurium",
		"Terbium",
		"Thallium",
		"Thorium",
		"Thulium",
		"Tin",
		"Titanium",
		"Tungsten",
		"Ununbium",
		"Ununhexium",
		"Ununoctium",
		"Ununpentium",
		"Ununquadium",
		"Ununseptium",
		"Ununtrium",
		"Ununium",
		"Uranium",
		"Vanadium",
		"Xenon",
		"Ytterbium",
		"Yttrium",
		"Zinc",
		"Zirconium",
	];

	private static $colorNames = [
		"amber",
		"amethyst",
		"apricot",
		"aqua",
		"aquamarine",
		"auburn",
		"azure",
		"beige",
		"black",
		"blue",
		"bronze",
		"brown",
		"buff",
		"burnt umber",
		"cardinal",
		"carmine",
		"celadon",
		"cerise",
		"cerulean",
		"charcoal",
		"chartreuse",
		"chocolate",
		"cinnamon",
		"color",
		"complementary",
		"copper",
		"coral",
		"cream",
		"crimson",
		"cyan",
		"dark",
		"denim",
		"desert sand",
		"ebony",
		"ecru",
		"eggplant",
		"emerald",
		"forest green",
		"fuchsia",
		"gold",
		"goldenrod",
		"gray",
		"green",
		"grey",
		"hot pink",
		"hue",
		"indigo",
		"ivory",
		"jade",
		"jet",
		"jungle green",
		"kelly green",
		"khaki",
		"lavender",
		"lemon",
		"light",
		"lilac",
		"lime",
		"magenta",
		"mahogany",
		"maroon",
		"mauve",
		"mustard",
		"navy blue",
		"ocher",
		"olive",
		"orange",
		"orchid",
		"pale",
		"pastel",
		"peach",
		"periwinkle",
		"persimmon",
		"pewter",
		"pink",
		"primary",
		"puce",
		"pumpkin",
		"purple",
		"rainbow",
		"red",
		"rose",
		"ruby",
		"russet",
		"rust",
		"saffron",
		"salmon",
		"sapphire",
		"scarlet",
		"sea green",
		"secondary",
		"sepia",
		"shade",
		"shamrock",
		"sienna",
		"silver",
		"spectrum",
		"slate",
		"steel blue",
		"tan",
		"tangerine",
		"taupe",
		"teal",
		"terracotta",
		"thistle",
		"tint",
		"tomato",
		"topaz",
		"turquoise",
		"ultramarine",
		"umber",
		"vermilion",
		"violet",
		"viridian",
		"wheat",
		"white",
		"wisteria",
		"yellow",
	];

    private static $fabricNames = [
        "Aertex",
        "Airdura",
        "Airguard",
        "Alençon lace",
        "Antique satin",
        "Argentan lace",
        "Argentella lace",
        "Armenian needlelace",
        "Baize",
        "Ballistic nylon",
        "Bamboo",
        "Ban-Lon",
        "Barathea",
        "Barkcloth",
        "Batik",
        "Batiste",
        "Battenberg lace",
        "Bedford cord",
        "Bengaline silk",
        "Beta cloth",
        "Bobbinet",
        "Boiled wool",
        "Bombazine",
        "Bouclé",
        "Braid",
        "Brilliantine",
        "Broadcloth",
        "Brocade",
        "Broderie Anglaise",
        "Buckram",
        "Bunting",
        "Burano lace",
        "Buratto lace",
        "Burlap",
        "C change",
        "Calico",
        "Cambric",
        "Camel's hair",
        "Camlet",
        "Canvas",
        "Capilene",
        "Carrickmacross lace",
        "Casement",
        "Cavalry twill",
        "Cedar bark",
        "Challis",
        "Chambray",
        "Chantilly lace",
        "Char cloth",
        "Charmeuse",
        "Charvet",
        "Cheesecloth",
        "Chenille",
        "Chiengora",
        "Chiffon",
        "Chino",
        "Chintz",
        "Cloqué",
        "Cloth of gold",
        "Coolmax",
        "Cordura",
        "Corduroy",
        "Cotton duck",
        "Coutel",
        "Crape (French = Crêpe)",
        "Crêpe-back satin",
        "Crêpe de Chine",
        "Cretonne",
        "Crochet",
        "Damask",
        "Darlexx",
        "Dazzle",
        "Denim",
        "Dimity",
        "Dobby",
        "Donegal tweed",
        "Dotted Swiss",
        "Double cloth",
        "Down feather",
        "Dowlas",
        "Drill",
        "Drugget",
        "Duck",
        "Dupioni silk",
        "Dungarees",
        "Dyneema",
        "Faille",
        "Faux fur",
        "Felt",
        "Filet/Lacis lace",
        "Fishnet",
        "Flannel",
        "Flannelette",
        "Fleece",
        "Foulard",
        "Fustian",
        "French Terry",
        "Gabardine",
        "Gannex",
        "Gauze",
        "Gazar",
        "Georgette",
        "Ghalamkar",
        "Gingham",
        "Gore-Tex",
        "Grenadine",
        "Grenfell Cloth",
        "Grosgrain",
        "Habutai",
        "Halas lace",
        "Haircloth",
        "Harris Tweed",
        "Heather knit",
        "Hemp",
        "Hessian",
        "Herringbone",
        "Himroo",
        "Hodden",
        "Holland cloth",
        "Hollie Point lace",
        "Hopsack",
        "Houndstooth check",
        "Intarsia",
        "Interlock Jersey",
        "Jacquard knit",
        "Jamdani",
        "Jersey",
        "Jaconet",
        "Lace",
        "Lamé",
        "Lampas",
        "Lantana",
        "Lanon",
        "Lawn cloth",
        "Lazzer",
        "Leather",
        "Leatherette",
        "Leno",
        "Limerick lace",
        "Linen",
        "Linsey-woolsey",
        "Loden",
        "Longcloth",
        "Loop knit",
        "Lumalive",
        "Mackinaw",
        "Madapolam",
        "Madras",
        "Malimo",
        "Marquisette",
        "Matelassé",
        "Melton",
        "Mesh",
        "Milliskin",
        "Mockado",
        "Moire",
        "Moleskin",
        "Monk's cloth",
        "Moquette",
        "Mouflon",
        "Mousseline",
        "Muslin",
        "Nankeen",
        "Neoprene",
        "Net",
        "Oilskin",
        "Organdy",
        "Organza",
        "Osnaburg",
        "Ottoman",
        "Oxford",
        "Omran",
        "Paduasoy",
        "Panné velvet",
        "Peau de Soie",
        "Percale",
        "Piqué",
        "Plissé",
        "Plush",
        "Point de France lace",
        "Point de Gaze lace",
        "Point de Venise lace",
        "Pointelle",
        "Polar fleece",
        "Pongee",
        "Poplin",
        "Punto in Aria lace",
        "Qiviut",
        "Quilting",
        "Raschel knit",
        "Rakematiz",
        "Rayadillo",
        "Rep",
        "Reticella lace",
        "Ribbon lace",
        "Rib knit",
        "Rib weave",
        "Rinzu",
        "Ripstop",
        "Ripstop nylon",
        "Russell cord",
        "Saga Nishiki",
        "Sailcloth",
        "Samite",
        "Sateen",
        "Satin",
        "Saye",
        "Scarlet",
        "Scrim",
        "Seersucker",
        "Serge",
        "Shantung",
        "Sharkskin",
        "Shot silk",
        "Silnylon",
        "Songket",
        "Stockinette",
        "Stub-tex",
        "Stuff",
        "Suede",
        "Surah",
        "SympaTex",
        "Taffeta",
        "Tais",
        "Tammana",
        "Tambour lace",
        "Tapestry",
        "Tartan",
        "Teneriffe lace",
        "Terrycloth",
        "Terry velour",
        "Ticking",
        "Toile",
        "Tricot knit",
        "Tulle netting",
        "Tweed",
        "Twill",
        "Ultrasuede",
        "Velour",
        "Velours du Kasaï",
        "Velvet",
        "Velveteen",
        "Venetian Lace",
        "Venetian Wool",
        "Ventile",
        "Vinyl coated polyester (PVC)",
        "Viyella",
        "Voile",
        "Wadmal",
        "Whipcord",
        "Wigan",
        "Windstopper",
        "Worcester",
        "Worsted wool",
        "Youghal lace",
        "Yarn",
        "Zephyr",
        "Zibeline",
        "Zorbeez",
        "Zoya silk",
    ];
}