<?php

namespace PlanetBundle\Repository;

use AppBundle\Descriptor\UseCaseEnum;

/**
 * BlueprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlueprintRepository extends \Doctrine\ORM\EntityRepository
{

	public function getByName($name)
	{
		return $this->getEntityManager()
			->createQuery(
				"SELECT b FROM PlanetBundle:Resource\Blueprint b WHERE b.description = '$name' ORDER BY b.id ASC"
			)
			->getOneOrNullResult();
	}

    public function getAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT b FROM PlanetBundle:Resource\Blueprint b ORDER BY b.id ASC"
            )
            ->getResult();
    }

    public function getByUseCase($useCase)
    {
        $conceptRepository = new ConceptRepository();
        $concepts = $conceptRepository->getByUseCase($useCase);

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('blue')
            ->from('PlanetBundle:Resource\Blueprint', 'blue')
            ->where('blue.concept IN (?1)')
            ->setParameter(1, $concepts)
            ->orderBy('blue.description', 'ASC')
        ;

        return $qb->getQuery()->getResult();
    }

    public function getWarehouseable()
    {
        $buildingUC = UseCaseEnum::LAND_BUILDING;
        $portableUC = UseCaseEnum::PORTABLES;
        return $this->getEntityManager()
            ->createQuery(
                "SELECT b FROM PlanetBundle:Resource\Blueprint b WHERE b.useCases LIKE '%$portableUC%' AND b.useCases NOT LIKE '%$buildingUC%' ORDER BY b.id ASC"
            )
            ->getResult();
    }

}
