<?php

namespace PlanetBundle\Repository;

use AppBundle\Descriptor\UseCaseEnum;

/**
 * BlueprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlueprintRepository extends \Doctrine\ORM\EntityRepository
{

	public function getByName($name)
	{
		return $this->getEntityManager()
			->createQuery(
				"SELECT b FROM PlanetBundle:Blueprint b WHERE b.description = '$name' ORDER BY b.id ASC"
			)
			->getOneOrNullResult();
	}

    public function getAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT b FROM PlanetBundle:Blueprint b ORDER BY b.id ASC"
            )
            ->getResult();
    }

    public function getByUseCase($useCase)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT b FROM PlanetBundle:Blueprint b WHERE b.useCases LIKE '%$useCase%' ORDER BY b.id ASC"
            )
            ->getResult();
    }

    public function getWarehouseable()
    {
        $buildingUC = UseCaseEnum::LAND_BUILDING;
        $portableUC = UseCaseEnum::PORTABLES;
        return $this->getEntityManager()
            ->createQuery(
                "SELECT b FROM PlanetBundle:Blueprint b WHERE b.useCases LIKE '%$portableUC%' AND b.useCases NOT LIKE '%$buildingUC%' ORDER BY b.id ASC"
            )
            ->getResult();
    }

}
