<?php

namespace PlanetBundle\Repository;

/**
 * BuildingProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingProjectRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @return \PlanetBundle\Entity\BuildingProject[[]
	 */
	public function getActiveSortedByPriority()
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT p FROM AppBundle:Planet\CurrentBuildingProject p ORDER BY p.priority ASC'
			)
			->getResult();
	}

    /**
     * @return \PlanetBundle\Entity\BuildingProject[[]
     */
//    public function getHistorySortedByTime()
//    {
//        return $this->getEntityManager()
//            ->createQuery(
//                'SELECT p FROM AppBundle:Planet\BuildingProject p WHERE p.historyRecord = true ORDER BY p.priority ASC'
//            )
//            ->getResult();
//    }
}
