<?php

namespace PlanetBundle\Repository;

/**
 * OreDepositRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OreDepositRepository extends \Doctrine\ORM\EntityRepository
{
}
