<?php

namespace PlanetBundle\Repository;

use PlanetBundle\Entity\Region;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeakRepository extends \Doctrine\ORM\EntityRepository
{

}
