<?php

namespace PlanetBundle\Repository;

use PlanetBundle\Entity\Peak;
use PlanetBundle\Entity\Region;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeakRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param integer $xcoord
     * @param integer $ycoord
     * @return Peak
     */
    public function findOrCreateByCoords($xcoord, $ycoord, $defaultHeight = 0) {
        $peak = $this->findOneBy([
            'xcoord' => $xcoord,
            'ycoord' => $ycoord,
        ]);
        if ($peak !== null) {
            return $peak;
        }
        $peak = new Peak();
        $peak->setXcoord($xcoord);
        $peak->setYcoord($ycoord);
        $peak->setHeight($defaultHeight);
        return $peak;
    }
}
