<?php

namespace PlanetBundle\Repository;

use PlanetBundle\Entity\Peak;
use PlanetBundle\Entity\Region;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param Region $region
     * @return Region[]
     */
	public function getRegionNeighbourhood(Region $region)
	{
	    return $this->findAll();
	    $c = $region->getPeakCenter()->getId();
	    $r = $region->getPeakRight()->getId();
	    $l = $region->getPeakLeft()->getId();
        return $this->getEntityManager()
//            ->createQuery(
//                "SELECT r FROM AppBundle:Planet\Region r WHERE "
//                . "(r.peakCenter=$c AND r.peakLeft=$l AND r.peakRight!=$r) OR "
//                . "(r.peakCenter=$c AND r.peakLeft!=$l AND r.peakRight=$r) OR "
//                . "(r.peakCenter!=$c AND r.peakLeft=$l AND r.peakRight=$r)"
//            )
            ->createQuery(
                "SELECT r FROM AppBundle:Region r, AppBundle:Planet\Region c WHERE "
                . "c.peakCenter=$c AND c.peakLeft=$l AND c.peakRight=$r AND ("
                . "(r.peakCenter=c.peakLeft AND r.peakRight=c.peakCenter) OR "
                . "(r.peakLeft=c.peakLeft AND r.peakRight=c.peakRight) OR "
                . "(r.peakCenter=c.peakRight AND r.peakLeft=c.peakCenter) "
                . ")"
            )
            ->getResult();
	}

	public function findByPeaks(Peak $regionC, Peak $regionL, Peak $regionR) {
	    $r = $this->findOneBy([
            'peakCenter' => $regionC,
            'peakLeft' => $regionL,
            'peakRight' => $regionR]);
	    if ($r) {
	        return $r;
        }
        $r = $this->findOneBy([
            'peakCenter' => $regionC,
            'peakLeft' => $regionR,
            'peakRight' => $regionL]);
        if ($r) {
            return $r;
        }
        $r = $this->findOneBy([
            'peakCenter' => $regionL,
            'peakLeft' => $regionC,
            'peakRight' => $regionR]);
        if ($r) {
            return $r;
        }
        $r = $this->findOneBy([
            'peakCenter' => $regionL,
            'peakLeft' => $regionR,
            'peakRight' => $regionC]);
        if ($r) {
            return $r;
        }
        $r = $this->findOneBy([
            'peakCenter' => $regionR,
            'peakLeft' => $regionC,
            'peakRight' => $regionL]);
        if ($r) {
            return $r;
        }
        return $this->findOneBy([
            'peakCenter' => $regionR,
            'peakLeft' => $regionL,
            'peakRight' => $regionC]);
    }

    public function getPeaksLeftOf(Peak $peak, $count = 1) {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM PlanetBundle:Peak p WHERE "
                . "p.xcoord >= :xmin AND p.xcoord <= :xmax AND p.ycoord >= :ymin AND p.ycoord <= :ymax"
            )
            ->setParameter('xmin', $peak->getXcoord()-$count)
            ->setParameter('xmax', $peak->getXcoord()+$count)
            ->setParameter('ymin', $peak->getYcoord()-$count)
            ->setParameter('ymax', $peak->getYcoord())
            ->getResult();
    }

    public function getPeaksRightOf(Peak $peak, $count = 1) {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM PlanetBundle:Peak p WHERE "
                . "p.xcoord >= :xmin AND p.xcoord <= :xmax AND p.ycoord >= :ymin AND p.ycoord <= :ymax"
            )
            ->setParameter('xmin', $peak->getXcoord()-$count)
            ->setParameter('xmax', $peak->getXcoord()+$count)
            ->setParameter('ymin', $peak->getYcoord())
            ->setParameter('ymax', $peak->getYcoord()+$count)
            ->getResult();
    }

}
