<?php

namespace PlanetBundle\Repository;
use AppBundle\Entity;

/**
 * SettlementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettlementRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll()
	{
		return $this->getEntityManager()
			->createQuery(
				"SELECT s FROM PlanetBundle:Settlement s"
			)
			->getResult();
	}

	public function getByHumanSupervisor(Entity\Human $human)
	{
		$id = $human->getId();
		return $this->getEntityManager()
			->createQuery(
				"SELECT s FROM PlanetBundle:Settlement s WHERE s.manager = '$id'"
			)
			->getResult();
	}
}
