<?php

namespace AppBundle\Repository\Planet;

/**
 * BuildingProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingProjectRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @return \AppBundle\Entity\Planet\BuildingProject[[]
	 */
	public function getAllSortedByPriority()
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT p FROM AppBundle:Planet\BuildingProject p ORDER BY p.priority ASC'
			)
			->getResult();
	}
}
