<?php

namespace AppBundle\Repository\Planet;

use AppBundle\Entity\Planet\Region;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeakRepository extends \Doctrine\ORM\EntityRepository
{

}
