<?php

namespace AppBundle\Repository\Planet;

use AppBundle\Entity;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{

	public function getRegionNeighbarhood(Entity\Planet\Region $region)
	{
		$regionIds = range($region->getUuid() + 1, $region->getUuid() + 20);
		$regions = [];
		foreach ($regionIds as $id) {
			$regions[] = $this->getByUuid($id);
		}
		return $regions;
	}

	public function getByUuid($uuid)
	{
		$region = $this->getEntityManager()->find(Entity\Planet\Region::class, $uuid);
		if (!$region) {
			$region = new Entity\Planet\Region($uuid);
//			$this->getEntityManager()->persist($region);
		}
		return $region;
	}
}
