<?php

namespace AppBundle\Repository\Planet;

use AppBundle\Entity\Planet\Peak;
use AppBundle\Entity\Planet\Region;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * TODO: prepsat aby to tahalo sousedy do nejake rozumne vzdalenosti
     *
     * @param Region $region
     * @return Region[]
     */
	public function getRegionNeighbarhood(Region $region)
	{
		return $this->findAll();
	}

	public function findByPeaks(Peak $regionC, Peak $regionL, Peak $regionR) {
        return $this->findOneBy([
            'peakCenter' => $regionC,
            'peakLeft' => $regionL,
            'peakRight' => $regionR]);
    }

}
