<?php

namespace AppBundle\Repository\Planet;

/**
 * SettlementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettlementRepository extends \Doctrine\ORM\EntityRepository
{
}
