###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql-space:
      image: mysql:5.7
      container_name: imperiumsandbox-mysql-space
      working_dir: /application-mysql-space
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=imperium
        - MYSQL_USER=imperator
        - MYSQL_PASSWORD=muaddib
        - DATABASE_URL=mysql://imperator:muaddib@mysql-space:3306/imperium
      ports:
        - "2002:3306"

    mysql-planet:
      image: mysql:5.7
      container_name: imperiumsandbox-mysql-planet
      working_dir: /application-mysql-planet
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=imperium_planet_test
        - MYSQL_USER=imperator
        - MYSQL_PASSWORD=muaddib
        - DATABASE_URL=mysql://imperator:muaddib@mysql-planet:3306/imperium_planet_test
      ports:
        - "2003:3306"

    mysql-planet2:
      image: mysql:5.7
      container_name: imperiumsandbox-mysql-planet2
      working_dir: /application-mysql-planet2
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=imperium_planet_test2
        - MYSQL_USER=imperator
        - MYSQL_PASSWORD=muaddib
        - DATABASE_URL=mysql://imperator:muaddib@mysql-planet2:3306/imperium_planet_test2
      ports:
        - "2004:3306"

    webserver:
      image: nginx:alpine
      container_name: imperiumsandbox-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "2000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: imperiumsandbox-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

