<?php

namespace PlanetBundle\Repository;

use PlanetBundle\Entity\Human;
use PlanetBundle\Entity\Peak;
use PlanetBundle\Entity\Region;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByHuman(Human $human) {
        return $this->findOneBy([
            'human' => $human,
        ]);
    }

}
