<?php

namespace AppBundle\Repository;

/**
 * BlueprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlueprintRepository extends \Doctrine\ORM\EntityRepository
{
}
