<?php

namespace AppBundle\Repository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @return \AppBundle\Entity\Planet\BuildingProject[[]
	 */
	public function getActiveSortedByPriority()
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT p FROM AppBundle:Planet\Job p ORDER BY p.priority ASC'
			)
			->getResult();
	}

}
