<?php

namespace AppBundle\Repository;

/**
 * ResourceDepositRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceDepositRepository extends \Doctrine\ORM\EntityRepository
{
}
