<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ResourceDeposit;

/**
 * ResourceDepositRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceDepositRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return ResourceDeposit[]
     */
    public function getAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT rd FROM AppBundle:ResourceDeposit rd"
            )
            ->getResult();
    }

    /**
     * @return ResourceDeposit[]
     */
    public function getEmpty()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT rd FROM AppBundle:ResourceDeposit rd where rd.amount = 0"
            )
            ->getResult();
    }
}
