<?php

namespace AppBundle\Repository;

/**
 * SolarSystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolarSystemRepository extends \Doctrine\ORM\EntityRepository
{
}
