planet:
    resource: "@PlanetBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

gamers:
    resource: '@AppBundle/Controller/GamerController.php'
    type: annotation
    prefix: gamer