services:

  maintainer:
    class: PlanetBundle\Maintainer\Maintainer
    public: true
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@maintainer_food'
      - '@maintainer_population'

  maintainer_food:
    class: PlanetBundle\Maintainer\FoodMaintainer
    public: true
    arguments:
      - '@doctrine.orm.entity_manager'

  maintainer_population:
    class: PlanetBundle\Maintainer\PopulationMaintainer
    public: true
    arguments:
      - '@doctrine.orm.entity_manager'

  PlanetBundle\Fixture\:
    resource: '../../../PlanetBundle/Fixture/'
    tags: ['doctrine.fixture.orm']

  PlanetBundle\EventListener\BeforeControllerListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }