<?php

namespace AppBundle\Doctrine;

use Doctrine\ORM\EntityManager;

class UuidEntityManager extends EntityManager
{
	public function __construct(\Doctrine\DBAL\Connection $conn, \Doctrine\ORM\Configuration $config, \Doctrine\Common\EventManager $eventManager)
	{
//		parent::__construct($conn, $config, $eventManager);
	}

	public function find($entityName, $id, $lockMode = null, $lockVersion = null)
	{
		throw new \Exception("It works!");
		return parent::find($entityName, $id, $lockMode, $lockVersion); // TODO: Change the autogenerated stub
	}


}