<?php

namespace AppBundle\Repository\Planet;

use AppBundle\Entity\Human;
use AppBundle\Entity\Planet\Peak;
use AppBundle\Entity\Planet\Region;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByHuman(Human $human) {
        return $this->findOneBy([
            'human' => $human,
        ]);
    }

}
